// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcsnxieqnpcjqqiajtvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjc254aWVxbnBjanFxaWFqdHZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTY1NzEsImV4cCI6MjA2NTQ3MjU3MX0.wLszInM0m6qlG9EV70CcIqhVk5BGQR7MI_pzQAJYtI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);